export { db } from "./client"

// Re-export all Prisma types for consumers
export type {
  User,
  Role,
  Permission,
  RolePermission,
  Category,
  Brand,
  Factory,
  Product,
  ProductPackagingOption,
  ProductImage,
  ProductPriceHistory,
  ShippingZone,
  ShippingRate,
  CartItem,
  Order,
  OrderItem,
  Payment,
  Shipment,
  Post,
  PostTag,
  Tag,
  QuoteRequest,
  Contact,
  TelegramLog,
  Setting,
  AuditLog,
  Account,
  VerificationToken,
  Session,
  DailyPriceBulletin,
  DailyPriceItem,
} from "@prisma/client"

export {
  CustomerType,
  CementType,
  CementGrade,
  PackagingType,
  StockStatus,
  OrderStatus,
  PaymentStatus,
  PaymentGateway,
  ShipmentStatus,
  TruckType,
  PostStatus,
  QuoteStatus,
  ContactStatus,
  ContactCategory,
  ContactSource,
  PackagingTier,
  Prisma,
} from "@prisma/client"
