export { db } from "./client"

// Re-export all Prisma types for consumers
export type {
  User,
  Role,
  Permission,
  RolePermission,
  Category,
  Brand,
  Factory,
  Product,
  ProductImage,
  ProductPriceHistory,
  ShippingZone,
  ShippingRate,
  Cart,
  CartItem,
  Order,
  OrderItem,
  OrderStatusHistory,
  Payment,
  Shipment,
  ShipmentStatusHistory,
  Post,
  PostTag,
  Tag,
  Comment,
  QuoteRequest,
  TelegramUser,
  TelegramMessage,
  Setting,
  AuditLog,
  Account,
  VerificationToken,
  Session,
} from "@prisma/client"

export {
  UserStatus,
  CustomerType,
  OrderStatus,
  PaymentStatus,
  PaymentGateway,
  ShipmentStatus,
  TruckType,
  PostStatus,
  CommentStatus,
  QuoteStatus,
  Prisma,
} from "@prisma/client"
